version: '2'
services:
  web:  
    restart: unless-stopped
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
#    entrypoint:
#      ["python", "manage.py","run"]
    env_file:
      - .env 
